### PR TITLE
Upgrade build Pipeline

### PR DESCRIPTION
**Pull request by AccaliaDeElementia**
Add appveyor builds to verify functionality on windows hosts

### CODE REVIEW

**Comment by AccaliaDeElementia** [comment]
..... dafuq? coveralls?! WHAT CHANGED?!

**Comment by Bluenaxela** [comment]
Well, Appveyor sure uses agonizingly slow VMs...
```
  1) Board model
       "before each" hook for "should add a board":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\sockrpg\test\unit\models\boardTests.js)```

**Comment by AccaliaDeElementia** [comment]
yeah that is.... a thing... it's why appveyor only has the one build environment while travis has 4 in its matrix.

**Comment by AccaliaDeElementia** [comment]
@yamikuronue, Are we good to merge this now? :-)

**Pull request merged**
